name: Ubuntu
description: Run anything on Ubuntu
version: 0.1.0
slug: ubuntu
arch:
  - amd64
  - aarch64
map:
  - config:rw
  - ssl:rw
  - share:rw
  - media:rw
  - backup:rw
  - addons:rw
ports:
  22/tcp: 8022
ports_description:
  22/tcp: SSH port
image: ghcr.io/coderadu/ubuntu-hassio-{arch}
