name: 'File Editor'
description: 'A better file editor for Home Assistant'
version: 0.1.0
slug: 'file-editor'
arch:
  - armv7
  - aarch64
  - amd64
startup: application
boot: auto
url: https://github.com/CodeRadu/hassio-addons/tree/main/file-editor
map:
  - 'config:rw'
  - 'ssl:rw'
  - 'share:rw'
  - 'media:rw'
  - 'backup:rw'
  - 'addons:rw'
ingress: true
ingress_port: 8080
panel_icon: 'mdi:file'
backup_exclude: ['*/*/']
build_from:
  amd64: ghcr.io/hassio-addons/ubuntu-base/amd64:7.2.0
  aarch64: ghcr.io/hassio-addons/ubuntu-base/aarch64:7.2.0
  armv7: ghcr.io/hassio-addons/ubuntu-base/armv7:7.2.0
