---
name: Coder
description: Coder in Home Assistant
version: 0.1.0
arch:
  - aarch64
  - amd64
startup: application
boot: auto
map:
  - config:rw
ports:
  - 3000/tcp: null
ports_description:
  3000/tcp: 'Web interface'
ingress: true
ingress_port: 3000
panel_icon: mdi:ubuntu
