name: Publish

on:
  push:
    branches: [main]
    paths:
      - code-server/**

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Login to Github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Publish code-server
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target code-server \
            --image ghcr.io/${{ github.actor }}/code-server-hassio
