name: 'Test'

on:
  push:
    paths:
      - 'code-server/**'

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target code-server \
            --docker-hub ${{ github.actor }}
